// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZa_t8NcfTVtXVwFwiGxGJWgTY44X5lVY',
    appId: '1:114266712759:android:8dff82600a5cfe6497bb32',
    messagingSenderId: '114266712759',
    projectId: 'redcabs-326d4',
    databaseURL: 'https://redcabs-326d4-default-rtdb.firebaseio.com',
    storageBucket: 'redcabs-326d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtuVYSy0cAZla6gQrvgvlFw1YQWTu64XA',
    appId: '1:114266712759:ios:505f4f8ceff6523b97bb32',
    messagingSenderId: '114266712759',
    projectId: 'redcabs-326d4',
    databaseURL: 'https://redcabs-326d4-default-rtdb.firebaseio.com',
    storageBucket: 'redcabs-326d4.appspot.com',
    iosClientId: '114266712759-0iu0nt2jcm7strj5bq10eo0smfp5quuu.apps.googleusercontent.com',
    iosBundleId: 'com.redcabs.com.redcabsMobile',
  );
}
